### ISSUE TITLE
请问页面是挂掉了吗？

### ISSUE THREAD

**Issue by zhoucumt** [vuefe/webpack2#42]
https://webpack.vuefe.cn/index/  该页面访问不了，上周收藏的时候还是好好的，现在打不开了

**Comment by dear-lizhihua** [comment]
是因为服务器不太稳定导致的，负责维护的同学好像最近比较忙。
所以建议你直接拉取整个项目到本地npm run dev运行，然后安装依赖。本地的项目是最新翻译，而且已经和webpack.js.org官网develop分支的样式保持同步。
